version: '3.9'
services:
  database:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  backend: 
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - JWT_SECRET=aRMVFmipbNvKvpWu9Ex6YrbPsJ4qAEvHyQx7cIQtCS3nqW2hh1AEb4gdR2pNTJj
      - MONGO_URI=mongodb://localhost:27017/to-do-list
      - PORT=3001
      - SALT=2
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/app
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5