version: '3.9'
services:
  database:
    image: mongo:4.4.6 
    container_name: database
    ports:
      - "27017:27017"
    restart: always
  backend: 
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - JWT_SECRET=aRMVFmipbNvKvpWu9Ex6YrbPsJ4qAEvHyQx7cIQtCS3nqW2hh1AEb4gdR2pNTJj
      - SERVER_PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/app
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
